# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# NeoForge Properties
minecraft_version=1.21.1
neoforge_version=21.1.250

# Mod Properties
mod_version=3.2.2+1.21.1-neoforge
maven_group=dev.velolib.radial
archives_base_name=radial
mod_id=radial

# Dependencies (NeoForge 1.21.1 builds from Modrinth Maven)
yacl_version=3.8.2+1.21.1-neoforge
mafglib_version=0.4.3+mc1.21.1
